system:
  default_device: "gpu"
  default_threads: 2

esm2:
  model_dir: ""
  model_name: "esm2_t33_650M_UR50D"

morfchibi:
  mode: "web" # normal, light, web

databases:
  swissprot_path: "/your/path/to/SwissProt"
  uniref90_path: "/your/path/to/uniref90"
