name: iDBRpred_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  
  - numpy
  - pandas
  - scikit-learn
  
  - pytorch=2.10.0
  - pytorch-cuda=12.8  
  
  - pip
  - pip:
    - tensorflow[and-cuda]==2.20.0
    - keras==3.13.2
    - transformers==5.0.0
    - fair-esm==2.0.0
    - pyyaml==6.0.3