#Debug mode
debug	0
#ESpritz path
ESpritz	/content/drive/MyDrive/Jing_all_work/Kurgan_lab/Project005_official/For_JMB_2026_Special/pre_submission/iDBRpred_code/draft2/feature_extractors/ESpritz/
#BLAST path 
PSIBLAST	/content/drive/MyDrive/Jing_all_work/Kurgan_lab/Project005_official/For_JMB_2026_Special/pre_submission/iDBRpred_code/draft2/feature_extractors/ncbi-blast-2.17.0+/bin
#input fasta file
Input	input.fasta
#output file
Output	output.txt   
# UniProt Swiss-Prot database
SwissProt	/content/drive/MyDrive/Jing_all_work/Bioinformatics_tools/databases/SwissProt/SwissProt
# UniProt UniRef90 database
UniRef90	/content/drive/MyDrive/Jing_all_work/Bioinformatics_tools/databases/uniref90/uniref90
# number of threads
threads	8
